--1.
SELECT name FROM MOVIESTAR
WHERE name IN
(SELECT name FROM MOVIEEXEC
WHERE NETWORTH > 10000000)
AND GENDER = 'F';

--2.
SELECT name FROM MOVIESTAR
WHERE name NOT IN
(SELECT name FROM MOVIEEXEC);

--3.
SELECT title FROM MOVIE
WHERE LENGTH > (SELECT LENGTH
				FROM MOVIE
				WHERE title = 'Star Wars');

--4.
SELECT title, name
FROM MOVIE, MOVIEEXEC
WHERE PRODUCERC# = CERT#
AND NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC
				WHERE name = 'Merv Griffin')
