--1.
SELECT title, name
FROM MOVIE INNER JOIN MOVIEEXEC
ON CERT# = PRODUCERC#
WHERE PRODUCERC# IN (SELECT PRODUCERC#
					FROM Movie
					WHERE title = 'Star Wars')

--2.
SELECT DISTINCT name
FROM MOVIEEXEC JOIN MOVIE ON CERT# = PRODUCERC#
JOIN STARSIN ON MOVIETITLE = TITLE
WHERE STARNAME = 'Harrison Ford' 

--3.
SELECT DISTINCT name, starname
FROM STARSIN JOIN MOVIE ON MOVIETITLE = TITLE
JOIN STUDIO ON NAME = STUDIONAME
ORDER BY name, STARNAME;

--4.
SELECT starname, A.networth, A.title 
FROM STARSIN JOIN (SELECT networth, title
FROM MOVIE JOIN MOVIEEXEC ON CERT# = PRODUCERC#
WHERE NETWORTH >= ALL (SELECT NETWORTH FROM MOVIEEXEC)) as A
ON MOVIETITLE = A.TITLE;


--5.
SELECT NAME, MOVIETITLE 
FROM MOVIESTAR
LEFT JOIN STARSIN ON STARNAME = NAME
WHERE MOVIETITLE IS NULL;


