--1.
SELECT * FROM SHIPS
JOIN CLASSES ON
ships.CLASS = CLASSES.CLASS;

--2.
SELECT * FROM SHIPS
RIGHT JOIN CLASSES ON
ships.CLASS = CLASSES.CLASS;

--3.
SELECT COUNTRY, name FROM SHIPS
JOIN CLASSES ON
SHIPS.CLASS = CLASSES.CLASS
LEFT JOIN OUTCOMES
ON SHIP = NAME
WHERE SHIP IS NULL;

--4.
SELECT SHIPS.NAME as 'Ship Name'
FROM SHIPS JOIN CLASSES
ON classes.CLASS = ships.CLASS
WHERE LAUNCHED = 1916 AND
NUMGUNS >= 7;

--5.
SELECT ship, battle, date
FROM SHIPS JOIN OUTCOMES ON
OUTCOMES.SHIP = SHIPS.NAME
JOIN BATTLES ON OUTCOMES.BATTLE = BATTLES.NAME
WHERE result = 'sunk';

--6.
SELECT * FROM
SHIPS JOIN CLASSES ON
SHIPS.NAME = CLASSES.CLASS AND
SHIPS.CLASS = CLASSES.CLASS;

--7.
SELECT CLASSES.CLASS, TYPE, COUNTRY, NUMGUNS, BORE, DISPLACEMENT FROM CLASSES
LEFT JOIN SHIPS ON
CLASSES.CLASS = SHIPS.CLASS
WHERE NAME IS NULL;

--8.
SELECT SHIPS.name, displacement, NUMGUNS, RESULT
FROM SHIPS JOIN OUTCOMES ON
OUTCOMES.SHIP = SHIPS.NAME
JOIN BATTLES ON OUTCOMES.BATTLE = BATTLES.NAME
JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE battle = 'North Atlantic';

