--1.
SELECT name FROM SHIPS
JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE DISPLACEMENT > 50000;

--2.
SELECT SHIPS.name as shipName, displacement, numguns
FROM SHIPS
JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
JOIN OUTCOMES ON OUTCOMES.SHIP = SHIPS.NAME
JOIN BATTLES  AS B ON OUTCOMES.BATTLE = B.NAME
WHERE B.NAME = 'Guadalcanal';

--3.
(SELECT DISTINCT COUNTRY 
FROM CLASSES
JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS WHERE TYPE = 'bb')
INTERSECT 
(SELECT DISTINCT COUNTRY 
FROM CLASSES
JOIN SHIPS ON SHIPS.CLASS = CLASSES.CLASS WHERE TYPE = 'bc');

--4.
SELECT A.NAME FROM (SELECT SHIPS.NAME, DATE FROM SHIPS
JOIN OUTCOMES ON OUTCOMES.SHIP = SHIPS.NAME
JOIN BATTLES ON OUTCOMES.BATTLE = BATTLES.NAME
WHERE RESULT = 'damaged')
 AS A JOIN
(SELECT SHIPS.NAME, DATE FROM SHIPS
JOIN OUTCOMES ON OUTCOMES.SHIP = SHIPS.NAME
JOIN BATTLES ON OUTCOMES.BATTLE = BATTLES.NAME)
AS B
ON A.DATE < B.DATE AND A.NAME = B. NAME;
