--SELECT MODEL, SPEED AS MHZ, HD AS GB FROM PC WHERE PRICE < 1200;
--SELECT DISTINCT TYPE FROM PRINTER; 
--SELECT DISTINCT MAKER FROM PRODUCT WHERE TYPE = 'Printer';
--SELECT MODEL, RAM, SCREEN FROM LAPTOP WHERE PRICE > 1000;

--SELECT CODE, MODEL, COLOR, TYPE, PRICE FROM PRINTER WHERE COLOR = 'y';

SELECT MODEL, SPEED, HD FROM PC WHERE CD IN ('12x', '16x') AND PRICE < 2000;


--SELECT ADDRESS FROM STUDIO WHERE NAME = 'MGM';
--SELECT  BIRTHDATE FROM MOVIESTAR WHERE NAME = 'Sandra Bulloc';

--SELECT STARNAME FROM STARSIN WHERE MOVIEYEAR = 1980 AND MOVIETITLE LIKE '%Empire%';

--SELECT NAME FROM MOVIEEXEC WHERE NETWORTH > 10000000;

--SELECT NAME FROM MOVIESTAR WHERE GENDER = 'M' OR ADDRESS LIKE '%Prefect Rd%';